local NetKeyMap = {}

NetKeyMap.KeyMap = {
	["Acceleration"] = "15",
	["Acceleration1"] = "72",
	["Acceleration2"] = "64",
	["Acceleration3"] = "67",
	["Action"] = "25",
	["AnimalCapacity"] = "177",
	["AnimationSpeed"] = "47",
	["AutoGetReward"] = "194",
	["BreakFx"] = "85",
	["BuyCount"] = "38",
	["CanGetReward"] = "111",
	["CheckerParam"] = "190",
	["CheckerType"] = "189",
	["CheckerValue"] = "191",
	["CoinProgress"] = "103",
	["CoinValue"] = "102",
	["Color"] = "88",
	["ConfigName"] = "139",
	["Confirm"] = "162",
	["ConfirmTime"] = "151",
	["CostCoin"] = "58",
	["CostRobux"] = "56",
	["Count"] = "31",
	["CountDown"] = "89",
	["CurrencySpent"] = "129",
	["CurrencyType"] = "131",
	["CurrentDisplayGetPowerFactor"] = "109",
	["CurrentRebirth"] = "105",
	["CurrentSpeed"] = "8",
	["CurrentValue"] = "167",
	["DeleteIDList"] = "145",
	["Description"] = "110",
	["Description1"] = "120",
	["Description2"] = "122",
	["Descritpion"] = "193",
	["DisplayAcceleration"] = "61",
	["DisplayGetCoinFactor"] = "59",
	["DisplayGetPowerFactor"] = "52",
	["DisplayMaxSpeedFactor"] = "71",
	["DisplayName"] = "150",
	["Distance"] = "5",
	["Duration"] = "39",
	["EffectOffsetX"] = "63",
	["EffectOffsetY"] = "76",
	["EffectOffsetZ"] = "73",
	["EffectPrefab"] = "84",
	["EggPrefab"] = "195",
	["End"] = "86",
	["EndIndex"] = "23",
	["EventName"] = "29",
	["EventParam"] = "134",
	["FX"] = "49",
	["Factor"] = "100",
	["FrameIndex"] = "18",
	["FromConfirm"] = "159",
	["FromPetInfoList"] = "157",
	["FromPlayerID"] = "154",
	["FromTradeList"] = "158",
	["GameAnimation"] = "79",
	["GameHeight"] = "65",
	["GameInfo"] = "28",
	["GamePhase"] = "19",
	["GameTimer"] = "20",
	["GetCoinFactor"] = "16",
	["GetCoinFactor1"] = "42",
	["GetCoinFactor2"] = "70",
	["GetCoinFactor3"] = "78",
	["GetExtraReward"] = "188",
	["GetPowerFactor1"] = "41",
	["GetPowerFactor2"] = "53",
	["GetPowerFactor3"] = "51",
	["HasSeasonPass"] = "186",
	["HipHeight"] = "66",
	["ID"] = "1",
	["Icon"] = "43",
	["Index"] = "141",
	["Indexable"] = "180",
	["Indexed"] = "181",
	["InstanceID"] = "93",
	["InstanceIDList"] = "146",
	["Interval"] = "48",
	["IsBuy"] = "101",
	["IsEquip"] = "96",
	["IsGetReward"] = "112",
	["IsLast"] = "192",
	["IsLock"] = "94",
	["IsPremium"] = "164",
	["IsRewardLoot"] = "198",
	["IsRobuxLoot"] = "199",
	["Key"] = "27",
	["LastMineDataIndex"] = "3",
	["LastMineIndex"] = "7",
	["Level"] = "99",
	["LevelName"] = "81",
	["LoginTime"] = "116",
	["LootCount"] = "200",
	["LootKey"] = "144",
	["LuckyGetPetLegendary1"] = "36",
	["LuckyGetPetSecret1"] = "44",
	["LuckyPetUpgrade1"] = "37",
	["MaxExistPowerFactor"] = "179",
	["MaxPoint"] = "183",
	["MaxRebirth"] = "108",
	["MaxSpeed"] = "14",
	["MaxSpeedFacto1"] = "60",
	["MaxSpeedFactor1"] = "35",
	["MaxSpeedFactor2"] = "68",
	["MaxSpeedFactor3"] = "74",
	["Message"] = "124",
	["Module"] = "24",
	["Name"] = "40",
	["NextDisplayGetPowerFactor"] = "104",
	["NextRebirth"] = "107",
	["OpenAuto"] = "197",
	["PackageID"] = "147",
	["PackageKey"] = "163",
	["Param"] = "26",
	["PartnerAnimation"] = "178",
	["PassProgress"] = "185",
	["PetID"] = "98",
	["PetList"] = "201",
	["PlaceID"] = "82",
	["PlaceIdWherePurchased"] = "130",
	["PlayerID"] = "90",
	["PlayerId"] = "126",
	["PlayerList"] = "21",
	["Point"] = "184",
	["Position"] = "6",
	["Power"] = "12",
	["Prefab"] = "54",
	["PreviewQuestID"] = "203",
	["ProductID"] = "32",
	["ProductId"] = "128",
	["ProductKey"] = "33",
	["ProductPurchaseChannel"] = "132",
	["Progress"] = "187",
	["PurchaseId"] = "127",
	["Rank"] = "92",
	["RankKey"] = "135",
	["Rarity"] = "50",
	["ReceiptInfo"] = "125",
	["RedeemCode"] = "140",
	["RemainCount"] = "118",
	["RequestID"] = "143",
	["RequireCoinValue"] = "106",
	["RequireDay"] = "123",
	["RequirePower"] = "46",
	["RequireRebirth"] = "83",
	["RequireTime"] = "113",
	["RequireValue"] = "168",
	["RewardCoin"] = "9",
	["RewardCount"] = "117",
	["RewardData"] = "136",
	["RewardID"] = "114",
	["RewardIcon"] = "202",
	["RewardIndex"] = "137",
	["RewardList"] = "119",
	["RewardPower"] = "45",
	["RewardType"] = "115",
	["Rotation"] = "142",
	["RunAnimation"] = "69",
	["SelectList"] = "161",
	["Signature"] = "165",
	["Size"] = "55",
	["Start"] = "87",
	["StartIndex"] = "22",
	["StartPos"] = "4",
	["StartSpeed"] = "13",
	["StartTime"] = "17",
	["State"] = "148",
	["Success"] = "133",
	["TargetPlayerID"] = "160",
	["Time"] = "91",
	["TimeStamp"] = "166",
	["Times"] = "196",
	["Timestamp"] = "172",
	["ToConfirm"] = "152",
	["ToPetInfoList"] = "156",
	["ToPlayerID"] = "155",
	["ToTradeList"] = "153",
	["ToolData"] = "138",
	["ToolID"] = "10",
	["ToolWorkDistance"] = "11",
	["TrackIndex"] = "2",
	["TrainOffsetX"] = "57",
	["TrainOffsetY"] = "62",
	["TrainOffsetZ"] = "77",
	["TrainingAnimation"] = "80",
	["TrainingOffsetX"] = "170",
	["TrainingOffsetY"] = "171",
	["TrainingOffsetZ"] = "169",
	["Type"] = "34",
	["UpgradeFactor"] = "95",
	["UpgradeLevel"] = "97",
	["UserID"] = "149",
	["Value"] = "30",
	["Weight"] = "121",
	["WorkDistance"] = "75",
	["World"] = "182",
}

-- 反向字典
NetKeyMap.ReserveKeyMap = nil

-- 临时字典，用于更新生成字典
NetKeyMap.KeyMapTemp = nil

function NetKeyMap:Init()
	NetKeyMap.ReserveKeyMap = {}
	for key, value in pairs(NetKeyMap.KeyMap) do
		NetKeyMap.ReserveKeyMap[value] = key
	end
	
	NetKeyMap.KeyMapTemp = {}
	for key, value in pairs(NetKeyMap.KeyMap) do
		NetKeyMap.KeyMapTemp[key] = value
	end
end

function NetKeyMap:GetCount()
	local count = 0
	for key, value in pairs(NetKeyMap.KeyMap) do
		count += 1
	end
	return count
end

function NetKeyMap:GetTempCount()
	local count = 0
	for key, value in pairs(NetKeyMap.KeyMapTemp) do
		count += 1
	end
	return count
end

return NetKeyMap
