-- game.ReplicatedStorage.GamePlay.RollerCoaster.Building.BuildingTrackUpEntrance
-- game.ReplicatedStorage.ScriptAlias.BuildingTrackUpEntrance
local BuildingTrackUpEntrance = require(game.ReplicatedStorage.GamePlay.RollerCoaster.Building.BuildingTrackUpEntrance)
return BuildingTrackUpEntrance