-- game.ReplicatedStorage.GamePlay.RollerCoaster.Building.BuildingTrackDownEntrance
-- game.ReplicatedStorage.ScriptAlias.BuildingTrackDownEntrance
local BuildingTrackDownEntrance = require(game.ReplicatedStorage.GamePlay.RollerCoaster.Building.BuildingTrackDownEntrance)
return BuildingTrackDownEntrance